name: Docs
on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: Update documentation
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Build documentation
        run: ./gradlew dokkaHtml
      - name: Add sample test page
        run: mv sample.html build/dokka/sample.html
      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/dokka
