name: Publish
on:
  push:
    branches: [ master ]

jobs:
  infer-version:
    name: Computing a new version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.nyx-infer.outputs.version }}
      newVersion: ${{ steps.nyx-infer.outputs.newVersion }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run nyx Infer
        id: nyx-infer
        uses: mooltiverse/nyx-github-action@main
        with:
          command: 'infer'
          changelogPath: 'CHANGELOG.md'
          verbosity: 'DEBUG'
          preset: 'extended'
          resume: 'true'
          releaseLenient: 'true'
          stateFile: '.nyx-state.json'
          summaryFile: '.nyx-summary.txt'
      - name: Run nyx Make
        uses: mooltiverse/nyx-github-action@main
        with:
          command: 'make'
          changelogPath: 'CHANGELOG.md'
          verbosity: 'DEBUG'
          preset: 'extended'
          resume: 'true'
          releaseLenient: 'true'
          stateFile: '.nyx-state.json'
          summaryFile: '.nyx-summary.txt'
      #      - name: Run nyx Mark
      #        uses: mooltiverse/nyx-github-action@main
      #        with:
      #          command: 'mark'
      #          changelogPath: 'CHANGELOG.md'
      #          preset: 'extended'
      #          verbosity: 'DEBUG'
      #          resume: 'true'
      #          releaseLenient: 'true'
      #          stateFile: '.nyx-state.json'
      #          summaryFile: '.nyx-summary.txt'

  publish-version:
    #    if: needs.infer-version.outputs.newVersion == true
    name: Publishing a new version
    runs-on: ubuntu-latest
    needs: infer-version
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run gradle publish
        run: ./gradlew publishAllPublicationsToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_projectVersion: ${{ needs.infer-version.outputs.version }}
          #          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
      - name: Nyx publish
        uses: mooltiverse/nyx-github-action@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NYX_RELEASE_TYPES_PUBLICATION_SERVICES: 'GITHUB'
          NYX_SERVICES_GITHUB_NAME: 'GITHUB'
          NYX_SERVICES_GITHUB_TYPE: 'GITHUB'
          NYX_SERVICES_GITHUB_OPTIONS_AUTHENTICATION_TOKEN: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"
          NYX_SERVICES_GITHUB_OPTIONS_REPOSITORY_NAME: 'webmonitor'
          NYX_SERVICES_GITHUB_OPTIONS_REPOSITORY_OWNER: 'ennioVisco'
        with:
          command: 'publish'
          changelogPath: 'CHANGELOG.md'
          preset: 'extended'
          verbosity: 'DEBUG'
          resume: 'true'
          releaseLenient: 'true'
          stateFile: '.nyx-state.json'
          summaryFile: '.nyx-summary.txt'

  update-readme:
    name: Updating README.md
    runs-on: ubuntu-latest
    needs: publish-version
    steps:
      - uses: actions/checkout@v3
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: com.enniovisco:webmonitor:\d+.\d+.\d+(-SNAPSHOT)?
          replace: com.enniovisco:webmonitor:${{ needs.infer-version.outputs.version }}
          include: "README.md"
      - uses: fregante/setup-git-user@v2
      - name: Push changes
        run: |
          git add README.md
          git commit -m "Updated README.md instructions with new package version" || true
          git push || true
