name: Publish
on: workflow_dispatch # Run only when manually triggered

jobs:
  infer-version:
    name: Publish a new version
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run nyx Infer
        uses: mooltiverse/nyx-github-action@main
        env:
          NYX_VERBOSITY: 'DEBUG'
        with:
          command: 'infer'
          changelogPath: 'CHANGELOG.md'
          preset: 'extended'
          resume: 'true'
          releaseLenient: 'true'
          stateFile: '.nyx-state.json'
          summaryFile: '.nyx-summary.txt'
      - name: Run nyx Make
        uses: mooltiverse/nyx-github-action@main
        env:
          NYX_VERBOSITY: 'DEBUG'
        with:
          command: 'make'
          changelogPath: 'CHANGELOG.md'
          preset: 'extended'
          resume: 'true'
          releaseLenient: 'true'
          stateFile: '.nyx-state.json'
          summaryFile: '.nyx-summary.txt'
      #      - name: Run nyx Mark
      #        uses: mooltiverse/nyx-github-action@main
      #        env:
      #          NYX_VERBOSITY: 'DEBUG'
      #        with:
      #          command: 'mark'
      #          changelogPath: 'CHANGELOG.md'
      #          preset: 'extended'
      #          resume: 'true'
      #          releaseLenient: 'true'
      #          stateFile: '.nyx-state.json'
      #          summaryFile: '.nyx-summary.txt'
      - name: Nyx publish
        id: nyx
        uses: mooltiverse/nyx-github-action@main
        env:
          NYX_VERBOSITY: 'DEBUG'
          NYX_SERVICES_GITHUB_NAME: 'GITHUB'
          NYX_SERVICES_GITHUB_TYPE: 'GITHUB'
          NYX_SERVICES_GITHUB_OPTIONS-AUTHENTICATION_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NYX_SERVICES_GITHUB_OPTIONS-REPOSITORY_NAME: 'webmonitor'
          NYX_SERVICES_GITHUB_OPTIONS-REPOSITORY_OWNER: 'ennioVisco'
        with:
          command: 'publish'
          changelogPath: 'CHANGELOG.md'
          preset: 'extended'
          resume: 'true'
          releaseLenient: 'true'
          stateFile: '.nyx-state.json'
          summaryFile: '.nyx-summary.txt'
