name: Publish
on: workflow_dispatch # Run only when manually triggered

jobs:
  infer-version:
    name: Computing a new version
    runs-on: ubuntu-latest
    outputs:
      newVersion: ${{ steps.nyx.outputs.newVersion }}
      version: ${{ steps.nyx.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run nyx Infer
        id: nyx-infer
        uses: mooltiverse/nyx-github-action@main
        with:
          command: 'infer'
          changelogPath: 'CHANGELOG.md'
          verbosity: 'DEBUG'
          preset: 'extended'
          resume: 'true'
          releaseLenient: 'true'
          stateFile: '.nyx-state.json'
          summaryFile: '.nyx-summary.txt'
      - name: Run nyx Make
        uses: mooltiverse/nyx-github-action@main
        with:
          command: 'make'
          changelogPath: 'CHANGELOG.md'
          verbosity: 'DEBUG'
          preset: 'extended'
          resume: 'true'
          releaseLenient: 'true'
          stateFile: '.nyx-state.json'
          summaryFile: '.nyx-summary.txt'
      - name: Run nyx Mark
        uses: mooltiverse/nyx-github-action@main
        with:
          command: 'mark'
          changelogPath: 'CHANGELOG.md'
          preset: 'extended'
          verbosity: 'DEBUG'
          resume: 'true'
          releaseLenient: 'true'
          stateFile: '.nyx-state.json'
          summaryFile: '.nyx-summary.txt'
      - name: Test dependencies
        run: echo ${{ steps.nyx.outputs.version }} - ${{ steps.nyx.outputs.newVersion }}


  publish-version:
    if: needs.infer-version.steps.nyx.outputs.newVersion == true
    name: Publishing a new version
    runs-on: ubuntu-latest
    needs: infer-version
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run gradle publish
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_project.version: ${{ needs.infer-version.steps.nyx.outputs.version }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_sonaTypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonaTypePassword: ${{ secrets.SONATYPE_PASSWORD }}
      - name: Nyx publish
        uses: mooltiverse/nyx-github-action@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NYX_RELEASE_TYPES_PUBLICATION_SERVICES: 'GITHUB'
          NYX_SERVICES_GITHUB_NAME: 'GITHUB'
          NYX_SERVICES_GITHUB_TYPE: 'GITHUB'
          NYX_SERVICES_GITHUB_OPTIONS_AUTHENTICATION_TOKEN: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"
          NYX_SERVICES_GITHUB_OPTIONS_REPOSITORY_NAME: 'webmonitor'
          NYX_SERVICES_GITHUB_OPTIONS_REPOSITORY_OWNER: 'ennioVisco'
        with:
          command: 'publish'
          changelogPath: 'CHANGELOG.md'
          preset: 'extended'
          verbosity: 'DEBUG'
          resume: 'true'
          releaseLenient: 'true'
          stateFile: '.nyx-state.json'
          summaryFile: '.nyx-summary.txt'
